"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(4, 8);
console.log("----Prbando metodos de Point------");
myPoint.toString();
myPoint.setX(10);
console.log(myPoint.getX());
myPoint.setY(25);
console.log(myPoint.getY());
console.log("----Probando metodos de Distancias------");
console.log('Distancia al punto de origen: ' + myPoint.distanceToOrigin());
var myPoint2 = new point_1.Point(11, 5);
console.log('Distancia de otro punto: ' + myPoint.calculateDistance(myPoint2));
